### PR TITLE
Add subcommand db_info

### PR DESCRIPTION
**Pull request by dfornika**
Addresses #37. Adds new sub-command `db_info` that reads an existing MentaLiST database and reports relevant statistics.

### CODE REVIEW

**Comment by dfornika** [comment]
Do you have any suggestions for other information that would be useful to extract from a database using this command? I was thinking it might be nice to be able to get the list of all locus IDs, but for cgMLST & wgMLST schemes that would be a lot of output, so I was thinking of making it optional with `-l` or `--locus_ids`.

It might also be nice to optionally produce the data in json format:

```json
{
  "mentalist_version": "0.2.2",
  "num_loci": 7,
  "locus_ids": ["aroC", "dnaN", "hemD", "hisD", "purE", "sucA", "thrA"]
}
```

**Comment by pedrofeijao** [comment]
The -l flag is a good idea, and also JSON, with a -j flag maybe, sounds nice to me.
Maybe the number of kmers in the database would be nice to show as well, it should not be hard to extract that info.

**Comment by dfornika** [comment]
Ok, I think that by default the output will be tab-separated, with the first column showing a label for the value:

```
mentalist_version    0.2.2
num_loci    7
num_kmers    3948
...etc
```

With the `-l` flag, we'll include `locus_ids`:

```
mentalist_version    0.2.2
num_loci    7
num_kmers    3948
locus_ids    aroC    dnaN    hemD    hisD    purE    sucA    thrA
...etc
```

...and the `-j` flag will make it JSON format:

```
{
  "mentalist_version": "0.2.2" 
  "num_loci": 7
  "num_kmers": 3948
  "locus_ids": ["aroC", "dnaN", "hemD", "hisD", "purE", "sucA", "thrA"]
  ...etc
}
```

Is there any sense in reporting the number of kmers for each locus, or just a global count for all loci?

**Comment by pedrofeijao** [comment]
The number of alleles per locus might be also interesting. With that, the number of kmers per locus could also be interesting.

**Comment by dfornika** [comment]
Ok, so maybe we could report that like this:

The `-l` flag could be `--locus_info` which includes:

```
locus_ids    aroC    dnaN    hemD    hisD    purE    sucA    thrA
num_alleles    28    45    39    22    54    68    34
num_kmers    352    432    321    483    542    283
```

...and we could group them together in JSON format like this:

```
"loci": [
  {
    "locus_id": "aroC",
    "num_alleles": 28,
    "num_kmers": 352
  },
    "locus_id": "dnaN",
    "num_alleles": 45,
    "num_kmers": 432
  },
...etc
]

**Comment by pedrofeijao** [comment]
Yes, that looks good.

**Pull request merged**
