### PR TITLE
Use conda for TravisCI testing environment

### LINKED ISSUE #50: TravisCI testing not working for mentalist_v0.1 branch
TravisCI test jobs on the `mentalist_v0.1` branch have all been failing with this error:

```
Executing the default test script
Package name determined from repository url to be MentaLiST
0.77s$ julia --color=yes -e 'Pkg.clone(pwd())'
INFO: Initializing package repository /home/travis/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: GitError(Code:ERROR, Class:Net, SSL error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in clone(::String, ::String, ::Base.LibGit2.CloneOptions) at ./libgit2/repository.jl:191
 in #clone#112(::String, ::Bool, ::Ptr{Void}, ::Nullable{Base.LibGit2.AbstractCredentials}, ::Function, ::String, ::String) at ./libgit2/libgit2.jl:327
 in (::Base.LibGit2.#kw##clone)(::Array{Any,1}, ::Base.LibGit2.#clone, ::String, ::String) at ./<missing>:0
 in (::Base.Pkg.Dir.##4#6{String,String})() at ./pkg/dir.jl:49
 in cd(::Base.Pkg.Dir.##4#6{String,String}, ::String) at ./file.jl:59
 in init(::String, ::String) at ./pkg/dir.jl:47
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:28
 in clone(::String) at ./pkg/pkg.jl:151
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
```

...which seems to be originating from some setting in the TravisCI julia environment.

@apetkau has suggested using a conda environment for TravisCI testing, similar to the one used in [staramr](https://github.com/phac-nml/staramr/blob/development/.travis.yml)

### PR DESCRIPTION
**Pull request by dfornika**
Fixes #50

### CODE REVIEW

**Comment by dfornika** [comment]
It looks like the conda environment is working, but we're running into a similar issue that we see sometimes on the conda-forge julia repo. If there's a ~10 minute period with no output during testing then TravisCI will stop the test run.

It looks like all of the scheme fasta files download, then it quits while the database is being generated.

I think we have two options: 
 1. Limit our testing to smaller datasets (ie. don't use real cgMLST schemes for testing)
 2. Use some sort of progress indicator (printing ............. to stdout) while the database is being generated

**Comment by pedrofeijao** [comment]
I like the idea of not testing the cgMLST, because they can take a long time. Is there a way to design the tests such the the cgMLST part only runs if we give a specific flag, or automatically every week or so?

**Comment by dfornika** [comment]
I don't know how to add those sorts of controls to the test runner, but I think we can look into it down the road. In the short-term maybe we can just remove the cgMLST parts from our test suite. I'll add that to this pull request.

**Comment by dfornika** [comment]
I've commented out the cgMLST portion and filled in a few more tests for C. difficile pubMLST analysis.

I changed the values for `votes` and `loci_votes` to match what was actually being returned. We might need to review those values to make sure that they're reasonable.

**Comment by dfornika** [comment]
I see a green checkmark so I'm going to merge this. We can continue to tweak the tests as necessary later.

**Pull request merged**
